### ISSUE TITLE
Version 1.4.0 is serving 1.3.0 source files

### ISSUE THREAD

**Issue by ted-rothrock** [mobileforming/WiremockClient#23]
Hey @bainfu, hope you're doing well!

I made a mistake in the podspec when releasing v1.4.0: The `s.source` property is still pointing at the `1.3.0` tag, so installing v1.4.0 actually gives you v1.3.0 source files. Would it be possible to merge @watkyn's PR and release v1.5.0 with a corrected podspec?

I'm happy to help, but I understand if you prefer to limit write access.

**Comment by bainfu** [comment]
I think you're an admin on this project.  If you can't do it, let's figure that out.

**Comment by trothrock** [comment]
@bainfu This what happens when you have multiple Github accounts 🤦 I do still have write access on this repo
