### ISSUE TITLE
Unable to publish 2.0

### ISSUE THREAD

**Issue by trothrock** [mobileforming/WiremockClient#28]
Hey @bainfu, v2.0 is ready to release, but I'm unable to push the podspec to the Cocoapods repo. The only email address listed as an owner of the pod is ted.rothrock@mobileforming.com (you can run `pod trunk info WiremockClient` to verify). I submitted a request to Cocoapods a while back, but they haven't responded. Would it be possible to resurrect that email long enough to add more owners? If possible, I'd like to add my personal email: theodore.rothrock@gmail.com

**Comment by bainfu** [comment]
Look at me... Look at me. Ted is the Captain now.
