### ISSUE TITLE
swift Graphql mocking

### ISSUE THREAD

**Issue by asifhasan002** [mobileforming/WiremockClient#38]
How can I mock graphql, Can you provided any tutorial please.

**Comment by mahabaleshwarhnr** [comment]
@asifhasan002  I will put my idea how you can do stubbing. Basically you can do any kind of stubbing in WireMock.  Grapqhql have header name called `operationName` or you can append custom header name.
- You can do server response based header matching.  
- You can also do request body matching. 

PS: I haven't tried practically. I believe this will work.
